language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-wordpress-project' ]; then cd .. && eval "mv $currentfolder generator-wordpress-project" && cd generator-wordpress-project; fi

